import { LegalPage, type LegalSection } from '@/components/common/LegalPage';

const sections: LegalSection[] = [
  { title: 'Introduction', paragraphs: ['This Privacy Policy explains how NYAYGSATHI handles information when you use our AI-powered civic and legal guidance platform. We aim to make government services, citizen rights, legal information, documents, complaints, and possible next steps easier to understand.'] },
  { title: 'Information We Collect', paragraphs: ['We collect information needed to provide, secure, improve, and support the service. The information we collect depends on the features you use and the choices you make.'] },
  { title: 'Personal Information', paragraphs: ['When you create an account or contact us, we may collect your name, email address, account credentials, support messages, and other information you choose to provide. Do not submit sensitive information unless it is necessary for your requested functionality.'] },
  { title: 'User-Submitted Problems and Documents', paragraphs: ['You may submit questions, descriptions of civic problems, notices, letters, applications, images, PDFs, and related information. Uploaded documents are private to your account and must not be publicly displayed. Please protect sensitive information and redact details that are not needed.'] },
  { title: 'Chat and Conversation History', paragraphs: ['We may retain questions, voice transcripts, chat messages, and generated responses so that we can provide requested features such as history, case tracking, and support. You can delete eligible content through the application or request deletion.'] },
  { title: 'Device and Technical Information', paragraphs: ['We may receive technical information such as browser type, device information, approximate usage times, language preference, error information, and security logs. We use this information to operate and protect the service.'] },
  { title: 'How We Use Information', paragraphs: ['We use information to provide requested analysis and guidance, maintain accounts, store documents and case history, respond to support requests, prevent misuse, improve reliability, and meet legal obligations. We do not use your information for unrelated purposes without an appropriate legal basis or notice.'] },
  { title: 'AI Processing', paragraphs: ['AI processing is used to interpret user-provided questions and documents and generate explanations, evidence checklists, or possible next steps. Third-party AI or API services should receive data only when required for the functionality you request. AI output may be incomplete or incorrect and must be verified with official sources or qualified professionals.'] },
  { title: 'Document Storage and Security', paragraphs: ['Documents and related analysis are stored according to the application’s current technical design and applicable requirements. We use reasonable administrative, technical, and organizational safeguards, but no online service can guarantee absolute security. Protect your password and do not share account access.'] },
  { title: 'Data Sharing and Third-Party Services', paragraphs: ['We may share information with service providers that help operate requested features, such as hosting, storage, security, communications, or AI processing. These providers should receive only the information reasonably needed for their role. We may also disclose information when required by law, to protect rights and safety, or as part of a business transfer.'] },
  { title: 'Data Retention', paragraphs: ['We retain information for as long as needed to provide the service, maintain legitimate records, resolve disputes, enforce terms, and meet legal or security requirements. Retention varies by data type and feature. Deletion requests may be subject to lawful exceptions or backup schedules.'] },
  { title: 'User Rights', paragraphs: ['Depending on applicable law, you may request access to, correction of, export of, or deletion of your personal information, and you may object to or restrict certain processing. Contact us through the support channel to make a request.'] },
  { title: 'Account and Data Deletion', paragraphs: ['You can request deletion of your account and associated personal information, documents, conversations, and case data. We will process the request within a reasonable period and explain any information that must be retained by law or for security purposes.'] },
  { title: 'Cookies and Similar Technologies', paragraphs: ['The application may use cookies or browser storage to maintain sessions, remember preferences such as language and theme, and support security. You can control cookies through browser settings, but some features may not work without essential storage.'] },
  { title: "Children's Privacy", paragraphs: ['NYAYGSATHI is not directed to children who cannot legally use the service in their jurisdiction. We do not knowingly collect personal information from children without appropriate authorization. Contact us if you believe a child has submitted information.'] },
  { title: 'Changes to This Privacy Policy', paragraphs: ['We may update this policy as the service, law, or our practices change. We will post the updated version with a new effective date. Continued use after an update means the revised policy applies to future use, subject to applicable law.'] },
  { title: 'Contact Us', paragraphs: ['For privacy questions, rights requests, or concerns about uploaded information, contact our support team at support@nayasathi.ai or through the Contact Us link in the application.'] },
];

export default function PrivacyPolicyPage() {
  return <LegalPage eyebrow="NYAYGSATHI legal" title="Privacy Policy" description="How we handle account information, civic questions, uploaded documents, and AI-assisted analysis." updated="August 21, 2026" sections={sections} />;
}
