import { LegalPage, type LegalSection } from '@/components/common/LegalPage';

const sections: LegalSection[] = [
  { title: 'Acceptance of Terms', paragraphs: ['By accessing or using NYAYGSATHI, you agree to these Terms of Service and our Privacy Policy. If you do not agree, do not use the service.'] },
  { title: 'Eligibility', paragraphs: ['You may use NYAYGSATHI only if you can form a binding agreement under the laws that apply to you. If you use the service for an organization, you confirm that you have authority to accept these terms for it.'] },
  { title: 'Description of NYAYGSATHI', paragraphs: ['NYAYGSATHI is an AI-powered civic and legal guidance platform that helps users understand government services, citizen rights, legal information, documents, complaints, and possible next steps.'] },
  { title: 'User Accounts', paragraphs: ['You are responsible for providing accurate account information, keeping your credentials secure, and all activity under your account. Notify us promptly if you believe your account has been accessed without permission.'] },
  { title: 'User Responsibilities', paragraphs: ['Use the service lawfully and honestly. Review generated information before relying on it, protect sensitive information, and provide only content you have the right to submit and process.'] },
  { title: 'User-Submitted Content', paragraphs: ['You retain ownership of content you submit. You grant NYAYGSATHI the limited permission needed to host, process, display to you, and provide the requested features. You are responsible for ensuring that your content does not violate law or another person’s rights.'] },
  { title: 'Uploaded Documents', paragraphs: ['Uploaded documents are private to your account and are not intended for public display. Do not upload information that is not necessary for the requested analysis. You must have permission to upload and process each document.'] },
  { title: 'AI-Generated Information', paragraphs: ['AI output may contain errors, omissions, outdated information, or misunderstandings. It is provided as general guidance and is not a guaranteed answer, decision, classification, deadline, or recommendation. You should verify important information with official sources.'] },
  { title: 'Legal and Civic Guidance Disclaimer', paragraphs: ['NYAYGSATHI provides AI-generated civic and legal information for general guidance. It is not a substitute for advice from a qualified legal professional, government authority, or other appropriate professional. Users should verify important information with official sources.'] },
  { title: 'No Attorney-Client Relationship', paragraphs: ['Using NYAYGSATHI, submitting a question, or receiving an AI response does not create an attorney-client, advocate-client, fiduciary, or other professional relationship between you and NYAYGSATHI.'] },
  { title: 'No Guarantee of Legal Outcomes', paragraphs: ['NYAYGSATHI does not guarantee approval, eligibility, relief, response times, legal outcomes, government decisions, or the accuracy and completeness of any generated information.'] },
  { title: 'Prohibited Activities', paragraphs: ['You must not misuse the service, attempt unauthorized access, interfere with its operation, upload malware, impersonate another person, submit unlawful or infringing content, scrape private data, or use generated information to harm others.'] },
  { title: 'Intellectual Property', paragraphs: ['NYAYGSATHI and its software, design, branding, and original materials are protected by applicable intellectual property laws. These terms grant you a limited right to use the service; they do not transfer ownership.'] },
  { title: 'Third-Party Services', paragraphs: ['The service may depend on third-party providers for infrastructure, communications, storage, security, or AI processing. Their availability and terms may affect features. Third-party services should process only data needed for the requested functionality.'] },
  { title: 'Service Availability', paragraphs: ['We may change, suspend, or discontinue features, and maintenance or events outside our control may cause interruptions. We will make reasonable efforts to keep the service useful, but continuous availability is not guaranteed.'] },
  { title: 'Account Suspension or Termination', paragraphs: ['We may suspend or terminate access when necessary to protect users, investigate misuse, comply with law, or address a violation of these terms. You may stop using the service and request account deletion at any time.'] },
  { title: 'Limitation of Liability', paragraphs: ['To the maximum extent permitted by law, NYAYGSATHI is not liable for indirect, incidental, special, consequential, or punitive loss, or for decisions made solely from AI-generated information. Nothing in these terms excludes liability that cannot legally be excluded.'] },
  { title: 'Changes to Terms', paragraphs: ['We may update these terms as the service or law changes. We will post the revised terms with an updated date. Your continued use after changes take effect means you accept the revised terms, subject to applicable law.'] },
  { title: 'Governing Law', paragraphs: ['These terms are governed by the laws applicable in India, without regard to conflict-of-law rules, unless mandatory local law requires otherwise. Courts with appropriate jurisdiction will resolve disputes.'] },
  { title: 'Contact Us', paragraphs: ['Questions about these terms can be sent to support@nayasathi.ai or through the Contact Us link in the application.'] },
];

export default function TermsPage() {
  return <LegalPage eyebrow="NYAYGSATHI legal" title="Terms of Service" description="The rules and limits that apply when you use NYAYGSATHI for civic and legal guidance." updated="August 21, 2026" sections={sections} />;
}
